import { cta, html, reason, recap } from './blocks';
import type { StarterPackTemplate } from './types';

/**
 * Section 2 : Onboarding et souscriptions — page Confluence 930971651.
 *
 * Invitations et liens de souscription, relance des parcours abandonnés, revue
 * puis validation des dossiers, confirmations de souscription signée et
 * demandes de modification de données.
 */
export const SECTION_02_ONBOARDING: StarterPackTemplate[] = [
  {
    slug: 'invitation',
    name: 'Invitation à souscrire',
    section: 'onboarding',
    recipient: 'investor',
    trigger: 'manual',
    origin:
      "Envoi manuel depuis le back-office (liste des souscriptions du fonds, action d'envoi de l'invitation), sur une part sans gabarit d'invitation dédié ; génère le lien de souscription personnel de l'investisseur",
    variables: [
      '$logo',
      '$appname',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$campaign',
      '$fund_type',
      '$link',
      '$contact_firstname',
      '$contact_lastname',
      '$contact_mail',
    ],
    proposedVariables: [
      {
        name: '$part_name',
        note: "nom de la part sur laquelle porte l'invitation, connue au point d'appel mais non passée",
      },
    ],
    fr: {
      subject: '$campaign - Votre invitation à souscrire',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        '<p>Vous êtes invité(e) à souscrire au fonds <strong>$campaign</strong> ($fund_type).</p>',
        "<p>Votre parcours de souscription est entièrement en ligne : renseignez vos informations, déposez vos justificatifs et signez électroniquement votre bulletin. Vous pouvez interrompre le parcours à tout moment et le reprendre là où vous vous étiez arrêté(e).</p>",
        cta('$link', 'Commencer ma souscription'),
        '<p>Votre interlocuteur $contact_firstname $contact_lastname se tient à votre disposition pour toute question à l\'adresse <a href="mailto:$contact_mail">$contact_mail</a>.</p>',
      ]),
    },
    en: {
      subject: '$campaign - Your invitation to subscribe',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>You are invited to subscribe to the fund <strong>$campaign</strong> ($fund_type).</p>',
        '<p>Your subscription journey is fully online: fill in your details, upload your supporting documents and sign your subscription form electronically. You may pause at any time and resume where you left off.</p>',
        cta('$link', 'Start my subscription'),
        '<p>Your contact $contact_firstname $contact_lastname remains available for any question at <a href="mailto:$contact_mail">$contact_mail</a>.</p>',
      ]),
    },
  },
  {
    slug: 'Onboarding-link',
    name: "Lien de démarrage d'onboarding",
    section: 'onboarding',
    recipient: 'team',
    trigger: 'auto',
    origin:
      'Création d\'une souscription depuis le back-office avec le réglage "Send mail at subscription creation" actif. Écart au CSV : le mail part vers l\'adresse interne du réglage "Mail for new subscriptions", pas vers le contact investisseur (l\'envoi aux contacts investisseur est commenté dans le code) ; le lien pointe vers la liste back-office des souscriptions du fonds',
    variables: [
      '$logo',
      '$appname',
      '$year',
      '$mirror',
      '$investor',
      '$campaign',
      '$link',
      '$subscription.amount',
    ],
    proposedVariables: [],
    fr: {
      subject: '$campaign - Souscription créée pour $investor, onboarding initié',
      html: html('fr', [
        '<p>Bonjour,</p>',
        "<p>Une souscription vient d'être créée sur le fonds <strong>$campaign</strong> pour l'investisseur <strong>$investor</strong>, pour un montant de <strong>$subscription.amount</strong>.</p>",
        "<p>Le parcours d'onboarding a été initié et le lien de souscription est prêt à être transmis à l'investisseur.</p>",
        cta('$link', 'Voir les souscriptions du fonds'),
      ]),
    },
    en: {
      subject: '$campaign - Subscription created for $investor, onboarding initiated',
      html: html('en', [
        '<p>Hello,</p>',
        '<p>A subscription has just been created on the fund <strong>$campaign</strong> for the investor <strong>$investor</strong>, for an amount of <strong>$subscription.amount</strong>.</p>',
        '<p>The onboarding journey has been initiated and the subscription link is ready to be sent to the investor.</p>',
        cta('$link', "View the fund's subscriptions"),
      ]),
    },
  },
  {
    slug: 'invitation-partner',
    name: "Invitation à poursuivre l'onboarding en cours",
    section: 'onboarding',
    recipient: 'investor',
    trigger: 'manual',
    origin:
      'Le distributeur, depuis une section du parcours d\'onboarding qu\'il remplit pour son investisseur, transmet le lien de reprise avec un message personnalisé (bouton "Envoyer à l\'investisseur")',
    variables: [
      '$logo',
      '$appname',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$campaign',
      '$link',
      '$message',
    ],
    proposedVariables: [
      {
        name: '$partnername',
        note: "nom du distributeur à l'origine de l'envoi, connu en session au point d'appel mais non passé",
      },
    ],
    fr: {
      subject: '$campaign - Poursuivez votre souscription en ligne',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        '<p>Votre conseiller a préparé votre dossier de souscription au fonds <strong>$campaign</strong> et vous invite à le compléter en ligne.</p>',
        '<p>$message</p>',
        "<p>Cliquez sur le bouton ci-dessous pour reprendre le parcours là où votre conseiller s'est arrêté : vérifiez les informations déjà renseignées, complétez les éléments manquants et déposez vos justificatifs.</p>",
        cta('$link', 'Poursuivre ma souscription'),
      ]),
    },
    en: {
      subject: '$campaign - Continue your online subscription',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>Your adviser has prepared your subscription file for the fund <strong>$campaign</strong> and invites you to complete it online.</p>',
        '<p>$message</p>',
        '<p>Click the button below to resume the journey where your adviser left off: review the information already provided, complete any missing items and upload your supporting documents.</p>',
        cta('$link', 'Continue my subscription'),
      ]),
    },
  },
  {
    slug: 'invitation-partner-direct',
    name: 'Envoi direct du lien de souscription',
    section: 'onboarding',
    recipient: 'investor',
    trigger: 'auto',
    origin:
      'Le distributeur en mode sans onboarding ("no onboarding") crée la souscription pour son investisseur depuis l\'espace distributeur ; le lien de souscription part automatiquement à la création',
    variables: [
      '$logo',
      '$appname',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$campaign',
      '$link',
      '$subscription.amount',
    ],
    proposedVariables: [
      {
        name: '$partnername',
        note: "nom du distributeur, connu en session au point d'appel mais non passé",
      },
    ],
    fr: {
      subject: '$campaign - Votre lien de souscription',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        '<p>Votre conseiller a initié pour vous une souscription au fonds <strong>$campaign</strong>, pour un montant de <strong>$subscription.amount</strong>.</p>',
        '<p>Pour finaliser cette souscription, cliquez sur le bouton ci-dessous : vous pourrez vérifier vos informations, déposer vos justificatifs puis signer électroniquement votre bulletin.</p>',
        cta('$link', 'Finaliser ma souscription'),
        '<p>Votre conseiller reste votre interlocuteur privilégié pour toute question sur cette souscription.</p>',
      ]),
    },
    en: {
      subject: '$campaign - Your subscription link',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>Your adviser has initiated a subscription to the fund <strong>$campaign</strong> on your behalf, for an amount of <strong>$subscription.amount</strong>.</p>',
        '<p>To finalise this subscription, click the button below: you will be able to review your details, upload your supporting documents and sign your subscription form electronically.</p>',
        cta('$link', 'Finalise my subscription'),
        '<p>Your adviser remains your primary contact for any question regarding this subscription.</p>',
      ]),
    },
  },
  {
    slug: 'abandoned-subscription',
    name: 'Relance de souscription non finalisée',
    section: 'onboarding',
    recipient: 'investor',
    trigger: 'auto',
    origin:
      "Cron (toutes les minutes) : le délai de relance paramétré sur le fonds (abandoned_sub_mail_hours) est dépassé et la souscription est restée incomplète, sans souscription finalisée plus récente du même investisseur. Écarts au code : un print_r de debug suivi d'un die interrompt le cron avant l'envoi (la relance ne part jamais en l'état) ; l'envoi utilise toujours l'email de l'investisseur même quand la cible calculée est le distributeur",
    variables: [
      '$logo',
      '$appname',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$fond',
      '$link',
    ],
    proposedVariables: [
      {
        name: '$subscription_date',
        note: "date de création de la souscription, connue au point d'appel mais non passée",
      },
    ],
    fr: {
      subject: '$fond - Votre souscription vous attend',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        "<p>Vous avez commencé une souscription au fonds <strong>$fond</strong> sans la finaliser. Votre dossier a été conservé en l'état : les informations déjà saisies et les documents déjà déposés sont enregistrés.</p>",
        '<p>Il vous suffit de reprendre le parcours là où vous vous étiez arrêté(e) pour compléter les derniers éléments et signer votre bulletin.</p>',
        cta('$link', 'Reprendre ma souscription'),
        '<p>Si vous rencontrez une difficulté dans le parcours, notre équipe se tient à votre disposition.</p>',
      ]),
    },
    en: {
      subject: '$fond - Your subscription is waiting for you',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>You started a subscription to the fund <strong>$fond</strong> without completing it. Your file has been kept as it stands: the information already entered and the documents already uploaded are saved.</p>',
        '<p>Simply resume the journey where you left off to complete the remaining items and sign your subscription form.</p>',
        cta('$link', 'Resume my subscription'),
        '<p>Should you encounter any difficulty, our team remains at your disposal.</p>',
      ]),
    },
  },
  {
    slug: 'onboarding-valid',
    name: 'Onboarding investisseur terminé à traiter',
    section: 'onboarding',
    recipient: 'team',
    trigger: 'auto',
    origin:
      'L\'investisseur finalise son parcours d\'onboarding et soumet sa souscription ; le mail part au contact onboarding du fonds (mail_validation_onboarding, contact de notification ou réglage "Mail confirmation KYC terminé") ou, si le fonds est en prévalidation réseau, aux validateurs du distributeur',
    variables: [
      '$logo',
      '$appname',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$subscriptionname',
      '$campaign',
      '$amount',
      '$partnername',
      '$partneruser',
      '$link',
    ],
    proposedVariables: [],
    fr: {
      subject: '$campaign - Dossier de souscription à traiter : $subscriptionname ($amount)',
      html: html('fr', [
        '<p>Bonjour,</p>',
        "<p>Un dossier de souscription vient d'être finalisé et attend votre revue :</p>",
        '<p><strong>Investisseur :</strong> $prenom $nom ($subscriptionname)<br><strong>Fonds :</strong> $campaign<br><strong>Montant :</strong> $amount<br><strong>Distributeur :</strong> $partnername ($partneruser)</p>',
        "<p>L'investisseur a complété l'ensemble du parcours d'onboarding et déposé ses justificatifs. Le dossier est prêt pour la revue des pièces et la validation du KYC.</p>",
        cta('$link', 'Examiner le dossier'),
      ]),
    },
    en: {
      subject: '$campaign - Subscription file awaiting review: $subscriptionname ($amount)',
      html: html('en', [
        '<p>Hello,</p>',
        '<p>A subscription file has just been completed and awaits your review:</p>',
        '<p><strong>Investor:</strong> $prenom $nom ($subscriptionname)<br><strong>Fund:</strong> $campaign<br><strong>Amount:</strong> $amount<br><strong>Distributor:</strong> $partnername ($partneruser)</p>',
        '<p>The investor has completed the full onboarding journey and uploaded the supporting documents. The file is ready for document review and KYC validation.</p>',
        cta('$link', 'Review the file'),
      ]),
    },
  },
  {
    slug: 'reopen',
    name: 'Souscription réouverte pour compléments',
    section: 'onboarding',
    recipient: 'investor',
    trigger: 'manual',
    origin:
      "Le distributeur, depuis l'écran de revue du dossier (espace distributeur, action de réouverture), renvoie la souscription à l'investisseur avec la liste des pièces et questions à corriger et un message d'accompagnement",
    variables: [
      '$logo',
      '$appname',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$campaign',
      '$subscriptionname',
      '$message',
      '$questions',
      '$link',
      '$contact_firstname',
      '$contact_lastname',
      '$contact_mail',
    ],
    proposedVariables: [],
    fr: {
      subject: '$campaign - Votre dossier de souscription nécessite des compléments',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        '<p>Votre dossier de souscription <strong>$subscriptionname</strong> au fonds <strong>$campaign</strong> a été examiné. Certains éléments nécessitent une correction ou un complément avant de pouvoir être validés :</p>',
        '<p>$questions</p>',
        '<p>$message</p>',
        '<p>Votre dossier a été rouvert : cliquez sur le bouton ci-dessous pour corriger les éléments signalés, puis validez à nouveau votre dossier.</p>',
        cta('$link', 'Compléter mon dossier'),
        '<p>Pour toute question, votre interlocuteur $contact_firstname $contact_lastname est joignable à l\'adresse <a href="mailto:$contact_mail">$contact_mail</a>.</p>',
      ]),
    },
    en: {
      subject: '$campaign - Your subscription file requires additional items',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>Your subscription file <strong>$subscriptionname</strong> for the fund <strong>$campaign</strong> has been reviewed. Some items require a correction or an additional element before they can be validated:</p>',
        '<p>$questions</p>',
        '<p>$message</p>',
        '<p>Your file has been reopened: click the button below to address the items listed above, then submit your file again.</p>',
        cta('$link', 'Complete my file'),
        '<p>For any question, your contact $contact_firstname $contact_lastname can be reached at <a href="mailto:$contact_mail">$contact_mail</a>.</p>',
      ]),
    },
  },
  {
    slug: 'souscription-valid',
    name: 'Accusé de validation du dossier de souscription',
    section: 'onboarding',
    recipient: 'investor',
    trigger: 'auto',
    origin:
      "L'investisseur termine et valide son dossier de souscription depuis son espace (étape de validation du parcours d'onboarding). Note code : la variable $link passée au gabarit pointe vers l'écran back-office de revue, inutilisable par l'investisseur ; utiliser $url pour l'appel à l'action",
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$campaign',
      '$subscriptionname',
      '$amount',
    ],
    proposedVariables: [],
    fr: {
      subject: '$campaign - Votre dossier de souscription a bien été transmis',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        '<p>Nous vous confirmons la bonne réception de votre dossier de souscription <strong>$subscriptionname</strong> au fonds <strong>$campaign</strong>, pour un montant de <strong>$amount</strong>.</p>',
        '<p>Votre dossier va maintenant être examiné par nos équipes. Une fois les vérifications réglementaires effectuées, vous recevrez un email vous invitant à signer électroniquement votre bulletin de souscription.</p>',
        "<p>Aucune action n'est attendue de votre part à ce stade.</p>",
        cta('$url', 'Suivre ma souscription'),
      ]),
    },
    en: {
      subject: '$campaign - Your subscription file has been received',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>We confirm receipt of your subscription file <strong>$subscriptionname</strong> for the fund <strong>$campaign</strong>, for an amount of <strong>$amount</strong>.</p>',
        '<p>Your file will now be reviewed by our teams. Once the regulatory checks have been completed, you will receive an email inviting you to sign your subscription form electronically.</p>',
        '<p>No action is required on your side at this stage.</p>',
        cta('$url', 'Track my subscription'),
      ]),
    },
  },
  {
    slug: 'validation-kyc-investor',
    name: 'KYC validé et signature disponible',
    section: 'onboarding',
    recipient: 'investor',
    trigger: 'manual',
    origin:
      "Un utilisateur GP valide le KYC de la souscription depuis le back-office (écran de revue du dossier). Écart au code : les variables $prenom et $nom passées au gabarit contiennent le contact du distributeur (ou restent vides sans distributeur), pas l'investisseur ; utiliser $investor.firstname et $investor.lastname",
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$investor.firstname',
      '$investor.lastname',
      '$campaign',
      '$subscriptionname',
    ],
    proposedVariables: [],
    fr: {
      subject: '$campaign - Votre dossier est validé, place à la signature',
      html: html('fr', [
        '<p>Bonjour $investor.firstname $investor.lastname,</p>',
        '<p>Bonne nouvelle : votre dossier de souscription <strong>$subscriptionname</strong> au fonds <strong>$campaign</strong> a été validé par nos équipes.</p>',
        '<p>La prochaine étape est la signature électronique de votre bulletin de souscription. Vous recevrez très prochainement un email dédié contenant votre lien de signature.</p>',
        cta('$url', 'Accéder à mon espace'),
        '<p>Notre équipe se tient à votre disposition pour toute question.</p>',
      ]),
    },
    en: {
      subject: '$campaign - Your file is validated, signature is next',
      html: html('en', [
        '<p>Dear $investor.firstname $investor.lastname,</p>',
        '<p>Good news: your subscription file <strong>$subscriptionname</strong> for the fund <strong>$campaign</strong> has been validated by our teams.</p>',
        '<p>The next step is the electronic signature of your subscription form. You will shortly receive a dedicated email containing your signature link.</p>',
        cta('$url', 'Access my portal'),
        '<p>Our team remains available for any question.</p>',
      ]),
    },
  },
  {
    slug: 'validation-kyc-signature-prete-partner',
    name: 'KYC validé et signature prête côté distributeur',
    section: 'onboarding',
    recipient: 'partner',
    trigger: 'manual',
    origin:
      "Un utilisateur GP valide le KYC d'une souscription apportée par un distributeur ; le mail part au distributeur (ou à l'utilisateur distributeur rattaché à la souscription) avant le mail investisseur",
    variables: [
      '$logo',
      '$appname',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$campaign',
      '$subscriptionname',
      '$link',
    ],
    proposedVariables: [
      {
        name: '$amount',
        note: "montant de la souscription, connu au point d'appel mais non passé",
      },
    ],
    fr: {
      subject: '$campaign - KYC validé pour $subscriptionname, signature en cours d\'envoi',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        '<p>Le dossier de souscription <strong>$subscriptionname</strong> sur le fonds <strong>$campaign</strong> a été validé par la société de gestion.</p>',
        "<p>Le bulletin de souscription va être transmis pour signature électronique. Vous pouvez suivre l'avancement de ce dossier depuis votre espace distributeur.</p>",
        cta('$link', 'Suivre mes souscriptions'),
      ]),
    },
    en: {
      subject: '$campaign - KYC validated for $subscriptionname, signature being sent',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>The subscription file <strong>$subscriptionname</strong> on the fund <strong>$campaign</strong> has been validated by the management company.</p>',
        '<p>The subscription form will now be sent out for electronic signature. You can track the progress of this file from your distributor portal.</p>',
        cta('$link', 'Track my subscriptions'),
      ]),
    },
  },
  {
    slug: 'confirmation-souscription',
    name: 'Confirmation de souscription signée avec documents',
    section: 'onboarding',
    recipient: 'investor',
    trigger: 'auto',
    origin:
      "La souscription est entièrement signée : le récapitulatif part à l'investisseur avec les documents signés en pièce jointe, en copie aux adresses cc_mail_validation de la part ou du fonds, et systématiquement à l'adresse de supervision InvestHub",
    variables: [
      '$logo',
      '$appname',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$campaign',
      '$subscriptionname',
      '$partname',
      '$fund_type',
      '$amount',
      '$fees',
      '$totalAmt',
      '$parts',
      '$docs',
      '$link',
      '$contact_firstname',
      '$contact_lastname',
      '$contact_mail',
    ],
    proposedVariables: [],
    fr: {
      subject: '$campaign - Votre souscription de $amount est confirmée',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        "<p>Nous avons le plaisir de vous confirmer votre souscription <strong>$subscriptionname</strong> au fonds <strong>$campaign</strong> ($fund_type). Votre bulletin est signé par l'ensemble des signataires.</p>",
        recap([
          ['Part', '<strong>$partname</strong>'],
          ['Montant souscrit', '<strong>$amount</strong>'],
          ['Frais', '$fees'],
          ['Total', '<strong>$totalAmt</strong>'],
          ['Nombre de parts', '$parts'],
        ]),
        '<p>Vous trouverez en pièce jointe les documents signés de votre souscription :</p>',
        '<p>$docs</p>',
        '<p>Ces documents restent disponibles à tout moment dans votre espace investisseur.</p>',
        cta('$link', 'Accéder à mon espace investisseur'),
        '<p>Votre interlocuteur $contact_firstname $contact_lastname reste à votre disposition à l\'adresse <a href="mailto:$contact_mail">$contact_mail</a>.</p>',
      ]),
    },
    en: {
      subject: '$campaign - Your subscription of $amount is confirmed',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>We are pleased to confirm your subscription <strong>$subscriptionname</strong> to the fund <strong>$campaign</strong> ($fund_type). Your subscription form has been signed by all signatories.</p>',
        recap([
          ['Share', '<strong>$partname</strong>'],
          ['Subscribed amount', '<strong>$amount</strong>'],
          ['Fees', '$fees'],
          ['Total', '<strong>$totalAmt</strong>'],
          ['Number of shares', '$parts'],
        ]),
        '<p>Please find attached the signed documents of your subscription:</p>',
        '<p>$docs</p>',
        '<p>These documents remain available at any time in your investor portal.</p>',
        cta('$link', 'Access my investor portal'),
        '<p>Your contact $contact_firstname $contact_lastname remains at your disposal at <a href="mailto:$contact_mail">$contact_mail</a>.</p>',
      ]),
    },
  },
  {
    slug: 'confirmation-souscription-prelevement',
    name: 'Confirmation de souscription en prélèvement',
    section: 'onboarding',
    recipient: 'investor',
    trigger: 'auto',
    origin:
      'Même point d\'appel que confirmation-souscription : la souscription est entièrement signée, le réglage Lemonway est actif et l\'investisseur a choisi le règlement par prélèvement SEPA (réponse "sdd" = Oui)',
    variables: [
      '$logo',
      '$appname',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$campaign',
      '$subscriptionname',
      '$partname',
      '$fund_type',
      '$amount',
      '$fees',
      '$totalAmt',
      '$parts',
      '$docs',
      '$link',
      '$contact_firstname',
      '$contact_lastname',
      '$contact_mail',
      '$investor.iban',
    ],
    proposedVariables: [
      {
        name: '$debit_date',
        note: "date prévisionnelle du prélèvement, non passée au point d'appel",
      },
    ],
    fr: {
      subject: '$campaign - Souscription confirmée, prélèvement de $totalAmt à venir',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        "<p>Nous vous confirmons votre souscription <strong>$subscriptionname</strong> au fonds <strong>$campaign</strong> ($fund_type). Votre bulletin est signé par l'ensemble des signataires.</p>",
        recap([
          ['Part', '<strong>$partname</strong>'],
          ['Montant souscrit', '<strong>$amount</strong>'],
          ['Frais', '$fees'],
          ['Total', '<strong>$totalAmt</strong>'],
          ['Nombre de parts', '$parts'],
        ]),
        "<p>Conformément à votre mandat de prélèvement SEPA, le montant total de <strong>$totalAmt</strong> sera prélevé sur votre compte bancaire (IBAN $investor.iban). Aucune action n'est attendue de votre part : veillez simplement à ce que votre compte soit approvisionné.</p>",
        '<p>Vous trouverez en pièce jointe les documents signés de votre souscription :</p>',
        '<p>$docs</p>',
        cta('$link', 'Accéder à mon espace investisseur'),
        '<p>Votre interlocuteur $contact_firstname $contact_lastname reste à votre disposition à l\'adresse <a href="mailto:$contact_mail">$contact_mail</a>.</p>',
      ]),
    },
    en: {
      subject: '$campaign - Subscription confirmed, direct debit of $totalAmt upcoming',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>We confirm your subscription <strong>$subscriptionname</strong> to the fund <strong>$campaign</strong> ($fund_type). Your subscription form has been signed by all signatories.</p>',
        recap([
          ['Share', '<strong>$partname</strong>'],
          ['Subscribed amount', '<strong>$amount</strong>'],
          ['Fees', '$fees'],
          ['Total', '<strong>$totalAmt</strong>'],
          ['Number of shares', '$parts'],
        ]),
        '<p>In accordance with your SEPA direct debit mandate, the total amount of <strong>$totalAmt</strong> will be debited from your bank account (IBAN $investor.iban). No action is required on your side: simply make sure your account is funded.</p>',
        '<p>Please find attached the signed documents of your subscription:</p>',
        '<p>$docs</p>',
        cta('$link', 'Access my investor portal'),
        '<p>Your contact $contact_firstname $contact_lastname remains at your disposal at <a href="mailto:$contact_mail">$contact_mail</a>.</p>',
      ]),
    },
  },
  {
    slug: 'subscription-signed',
    name: 'Souscription signée, notification interne',
    section: 'onboarding',
    recipient: 'team',
    trigger: 'auto',
    origin:
      'Retour de signature électronique (webhook du prestataire de signature) indiquant que tous les signataires ont signé le bulletin ; envoi à l\'adresse du réglage "Email for notifications"',
    variables: [
      '$logo',
      '$appname',
      '$year',
      '$mirror',
      '$fund.name',
      '$subscriptionname',
      '$subscription',
      '$investor.name',
      '$investor.parent.name',
    ],
    proposedVariables: [
      {
        name: '$link',
        note: "lien direct vers l'écran de la souscription, non passé au point d'appel",
      },
      {
        name: '$amount',
        note: "montant de la souscription, connu au point d'appel mais non passé",
      },
    ],
    fr: {
      subject: '$fund.name - Souscription $subscription entièrement signée ($subscriptionname)',
      html: html('fr', [
        '<p>Bonjour,</p>',
        "<p>Le bulletin de souscription suivant vient d'être signé par l'ensemble des signataires :</p>",
        '<p><strong>Fonds :</strong> $fund.name<br><strong>Souscription :</strong> $subscription - $subscriptionname<br><strong>Investisseur :</strong> $investor.name</p>',
        "<p>Le statut de la souscription a été mis à jour et les documents signés sont en cours de récupération. Les éventuelles étapes de paiement et l'envoi des documents post-signature se déclenchent automatiquement.</p>",
        cta('$link', 'Ouvrir la souscription'),
      ]),
    },
    en: {
      subject: '$fund.name - Subscription $subscription fully signed ($subscriptionname)',
      html: html('en', [
        '<p>Hello,</p>',
        '<p>The following subscription form has just been signed by all signatories:</p>',
        '<p><strong>Fund:</strong> $fund.name<br><strong>Subscription:</strong> $subscription - $subscriptionname<br><strong>Investor:</strong> $investor.name</p>',
        '<p>The subscription status has been updated and the signed documents are being retrieved. Any payment steps and the post-signature document delivery are triggered automatically.</p>',
        cta('$link', 'Open the subscription'),
      ]),
    },
  },
  {
    slug: 'new-subscription-notification',
    name: 'Nouvelle souscription, alerte interne',
    section: 'onboarding',
    recipient: 'team',
    trigger: 'auto',
    origin:
      'Une nouvelle souscription est enregistrée sur un fonds ; envoi aux adresses du réglage "Mail notification nouvelle souscription" (liste séparée par des points-virgules)',
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$investor',
      '$partner',
      '$campaign',
      '$fund_type',
      '$amount',
    ],
    proposedVariables: [
      {
        name: '$link',
        note: "lien direct vers la souscription dans le back-office, non passé au point d'appel",
      },
    ],
    fr: {
      subject: '$campaign - Nouvelle souscription de $amount ($investor)',
      html: html('fr', [
        '<p>Bonjour,</p>',
        "<p>Une nouvelle souscription vient d'être enregistrée :</p>",
        '<p><strong>Fonds :</strong> $campaign ($fund_type)<br><strong>Investisseur :</strong> $investor<br><strong>Montant :</strong> $amount<br><strong>Distributeur :</strong> $partner</p>',
        '<p>Le dossier suivra les étapes habituelles : onboarding, revue, validation du KYC puis signature. Vous serez notifié aux jalons suivants.</p>',
        cta('$url', 'Ouvrir le back-office'),
      ]),
    },
    en: {
      subject: '$campaign - New subscription of $amount ($investor)',
      html: html('en', [
        '<p>Hello,</p>',
        '<p>A new subscription has just been recorded:</p>',
        '<p><strong>Fund:</strong> $campaign ($fund_type)<br><strong>Investor:</strong> $investor<br><strong>Amount:</strong> $amount<br><strong>Distributor:</strong> $partner</p>',
        '<p>The file will follow the usual steps: onboarding, review, KYC validation and signature. You will be notified at each milestone.</p>',
        cta('$url', 'Open the back office'),
      ]),
    },
  },
  {
    slug: 'change-confirm',
    name: 'Demande de modification de données validée',
    section: 'onboarding',
    recipient: 'investor',
    trigger: 'manual',
    origin:
      "Le back-office valide une demande de modification de données rattachée à une souscription (écran des données actives) ; la donnée est appliquée à la souscription et, si demandé, propagée aux autres souscriptions et à la fiche investisseur",
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$investor.firstname',
      '$investor.lastname',
      '$subscription',
      '$campaign.name',
    ],
    proposedVariables: [
      {
        name: '$info',
        note: "nature de la donnée modifiée (adresse, IBAN, téléphone…), connue au point d'appel via la demande mais non passée",
      },
    ],
    fr: {
      subject: 'Votre demande de modification est validée (souscription $subscription)',
      html: html('fr', [
        '<p>Bonjour $investor.firstname $investor.lastname,</p>',
        '<p>Votre demande de modification de données concernant votre souscription <strong>$subscription</strong> au fonds <strong>$campaign.name</strong> a été validée.</p>',
        '<p>Les nouvelles informations sont désormais prises en compte et visibles dans votre espace investisseur.</p>',
        cta('$url', 'Consulter mes informations'),
        '<p>Notre équipe se tient à votre disposition pour toute question.</p>',
      ]),
    },
    en: {
      subject: 'Your data change request has been approved (subscription $subscription)',
      html: html('en', [
        '<p>Dear $investor.firstname $investor.lastname,</p>',
        '<p>Your data change request regarding your subscription <strong>$subscription</strong> to the fund <strong>$campaign.name</strong> has been approved.</p>',
        '<p>The updated information is now in effect and visible in your investor portal.</p>',
        cta('$url', 'View my information'),
        '<p>Our team remains available for any question.</p>',
      ]),
    },
  },
  {
    slug: 'change-refuse',
    name: 'Demande de modification de données refusée',
    section: 'onboarding',
    recipient: 'investor',
    trigger: 'manual',
    origin:
      "Le back-office refuse une demande de modification de données rattachée à une souscription, avec un motif saisi par l'opérateur (écran des données actives de la souscription)",
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$investor.firstname',
      '$investor.lastname',
      '$subscription',
      '$campaign.name',
      '$message',
    ],
    proposedVariables: [
      {
        name: '$info',
        note: "nature de la donnée concernée (adresse, IBAN, téléphone…), connue au point d'appel via la demande mais non passée",
      },
    ],
    fr: {
      subject:
        "Votre demande de modification n'a pas pu être validée (souscription $subscription)",
      html: html('fr', [
        '<p>Bonjour $investor.firstname $investor.lastname,</p>',
        "<p>Votre demande de modification de données concernant votre souscription <strong>$subscription</strong> au fonds <strong>$campaign.name</strong> n'a pas pu être validée, pour le motif suivant :</p>",
        reason('$message'),
        '<p>Vos informations actuelles restent inchangées. Vous pouvez soumettre une nouvelle demande depuis votre espace investisseur en tenant compte de ce motif.</p>',
        cta('$url', 'Accéder à mon espace'),
        '<p>Notre équipe se tient à votre disposition pour toute question.</p>',
      ]),
    },
    en: {
      subject: 'Your data change request could not be approved (subscription $subscription)',
      html: html('en', [
        '<p>Dear $investor.firstname $investor.lastname,</p>',
        '<p>Your data change request regarding your subscription <strong>$subscription</strong> to the fund <strong>$campaign.name</strong> could not be approved, for the following reason:</p>',
        reason('$message'),
        '<p>Your current information remains unchanged. You may submit a new request from your investor portal, taking this reason into account.</p>',
        cta('$url', 'Access my portal'),
        '<p>Our team remains available for any question.</p>',
      ]),
    },
  },
  {
    slug: 'notify-change',
    name: 'Demande de modification de données reçue',
    section: 'onboarding',
    recipient: 'team',
    trigger: 'auto',
    origin:
      "Un investisseur soumet depuis son espace une demande de modification de ses données (adresse, IBAN, téléphone…) rattachée à une souscription ; envoi aux adresses du champ subchanges_mail du fonds (liste séparée par des points-virgules)",
    variables: [
      '$logo',
      '$appname',
      '$year',
      '$mirror',
      '$investor',
      '$info',
      '$subscription',
      '$campaign.name',
      '$link',
    ],
    proposedVariables: [],
    fr: {
      subject: '$campaign.name - Demande de modification de données à traiter ($investor)',
      html: html('fr', [
        '<p>Bonjour,</p>',
        "<p>Une demande de modification de données vient d'être soumise et attend votre traitement :</p>",
        '<p><strong>Investisseur :</strong> $investor<br><strong>Souscription :</strong> $subscription<br><strong>Fonds :</strong> $campaign.name<br><strong>Donnée concernée :</strong> $info</p>',
        "<p>La demande et ses éventuels justificatifs sont consultables depuis l'écran des données actives de la souscription, où vous pouvez la valider ou la refuser. L'investisseur sera notifié de votre décision.</p>",
        cta('$link', 'Traiter la demande'),
      ]),
    },
    en: {
      subject: '$campaign.name - Data change request awaiting review ($investor)',
      html: html('en', [
        '<p>Hello,</p>',
        '<p>A data change request has just been submitted and awaits your review:</p>',
        '<p><strong>Investor:</strong> $investor<br><strong>Subscription:</strong> $subscription<br><strong>Fund:</strong> $campaign.name<br><strong>Data concerned:</strong> $info</p>',
        "<p>The request and any supporting documents can be reviewed from the subscription's active data screen, where you can approve or reject it. The investor will be notified of your decision.</p>",
        cta('$link', 'Review the request'),
      ]),
    },
  },
  {
    slug: 'docs-available',
    name: 'Mise à disposition des documents de souscription',
    section: 'onboarding',
    recipient: 'investor',
    trigger: 'manual',
    origin:
      'Un utilisateur GP met les documents de souscription à disposition depuis la fiche de la souscription (action d\'envoi des documents) ; les éventuels signataires sont positionnés au préalable si le réglage "Set signers before sending docs" est actif',
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$investor.firstname',
      '$investor.lastname',
      '$fund.name',
      '$subscription.name',
    ],
    proposedVariables: [
      {
        name: '$docs',
        note: "liste des documents mis à disposition, non passée au point d'appel",
      },
    ],
    fr: {
      subject: '$fund.name - Vos documents de souscription sont disponibles',
      html: html('fr', [
        '<p>Bonjour $investor.firstname $investor.lastname,</p>',
        '<p>Les documents de votre souscription <strong>$subscription.name</strong> au fonds <strong>$fund.name</strong> sont désormais disponibles dans votre espace investisseur.</p>',
        '<p>Nous vous invitons à en prendre connaissance dès maintenant. Si une signature est attendue de votre part, elle vous sera proposée directement depuis votre espace.</p>',
        cta('$url', 'Consulter mes documents'),
        '<p>Notre équipe se tient à votre disposition pour toute question.</p>',
      ]),
    },
    en: {
      subject: '$fund.name - Your subscription documents are available',
      html: html('en', [
        '<p>Dear $investor.firstname $investor.lastname,</p>',
        '<p>The documents of your subscription <strong>$subscription.name</strong> to the fund <strong>$fund.name</strong> are now available in your investor portal.</p>',
        '<p>We invite you to review them at your convenience. If a signature is required on your side, it will be offered directly from your portal.</p>',
        cta('$url', 'View my documents'),
        '<p>Our team remains available for any question.</p>',
      ]),
    },
  },
];
