import { cta, highlight, html } from './blocks';
import type { ProposedVariable, StarterPackTemplate } from './types';

/**
 * Section 7 : Distributions, capital accounts et déblocages — page Confluence 930709507.
 *
 * Avis de distribution (souscription unique ou regroupée), mise à disposition et
 * relance des capital accounts, et avis de déblocage de parts.
 */

const SUBSCRIPTION_NAMES: ProposedVariable = {
  name: '$subscription_names',
  note: "liste des souscriptions couvertes par l'envoi, non passée au gabarit",
};

export const SECTION_07_DISTRIBUTIONS: StarterPackTemplate[] = [
  {
    slug: 'new_distrib',
    name: 'Avis de distribution',
    section: 'distributions',
    recipient: 'investor',
    trigger: 'manual',
    origin:
      "Notification d'une distribution aux investisseurs depuis le back office, Fonds puis Distributions, action Notifier, avec l'avis PDF en pièce jointe",
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$campaign',
      '$subscription.name',
      '$distribname',
      '$date',
      '$distrib_amount',
      '$amount_per_share',
      '$nbshares',
      '$share_name',
      '$charges',
      '$pitch',
    ],
    proposedVariables: [],
    fr: {
      subject: '$campaign - Avis de distribution : $distrib_amount',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        "<p>Le fonds <strong>$campaign</strong> procède à une distribution en date du <strong>$date</strong>. Au titre de votre souscription <strong>$subscription.name</strong>, le montant qui vous revient s'élève à :</p>",
        highlight('$distrib_amount'),
        '<p>$pitch Ce montant correspond à $amount_per_share par part, sur les $nbshares parts $share_name que vous détenez. Votre avis de distribution, joint à ce message, détaille le calcul et les modalités de versement.</p>',
        "<p>Aucune action n'est attendue de votre part.</p>",
        cta('$url', 'Consulter mon espace investisseur'),
        '<p>Notre équipe se tient à votre disposition pour toute question sur cette distribution.</p>',
      ]),
    },
    en: {
      subject: '$campaign - Distribution notice: $distrib_amount',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>The fund <strong>$campaign</strong> is making a distribution dated <strong>$date</strong>. Under your subscription <strong>$subscription.name</strong>, the amount payable to you is:</p>',
        highlight('$distrib_amount'),
        '<p>$pitch This amount corresponds to $amount_per_share per share, based on the $nbshares $share_name shares you hold. Your distribution notice, attached to this message, details the calculation and the payment terms.</p>',
        '<p>No action is required on your side.</p>',
        cta('$url', 'Access my investor portal'),
        '<p>Our team remains available for any question regarding this distribution.</p>',
      ]),
    },
  },
  {
    slug: 'new_distrib_bulk',
    name: 'Avis de distribution regroupé',
    section: 'distributions',
    recipient: 'investor',
    trigger: 'manual',
    origin:
      "Notification d'une distribution depuis le back office quand plusieurs souscriptions du même investisseur sont regroupées dans un même envoi : un email unique, avec un avis PDF par souscription ou une notice combinée selon paramétrage",
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$campaign',
      '$distribname',
      '$date',
      '$pitch',
    ],
    proposedVariables: [
      {
        name: '$distrib_total_amount',
        note: "total distribué à l'investisseur toutes souscriptions confondues, non calculé au point d'appel",
      },
      SUBSCRIPTION_NAMES,
    ],
    fr: {
      subject: '$campaign - Avis de distribution sur vos souscriptions',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        "<p>Le fonds <strong>$campaign</strong> procède à une distribution en date du <strong>$date</strong>. Cette distribution concerne plusieurs de vos souscriptions ($subscription_names) et le montant total qui vous revient s'élève à :</p>",
        highlight('$distrib_total_amount'),
        '<p>$pitch Les avis de distribution joints à ce message détaillent, pour chacune de vos souscriptions, le montant distribué et les modalités de versement.</p>',
        "<p>Aucune action n'est attendue de votre part.</p>",
        cta('$url', 'Consulter mon espace investisseur'),
        '<p>Notre équipe se tient à votre disposition pour toute question sur cette distribution.</p>',
      ]),
    },
    en: {
      subject: '$campaign - Distribution notice across your subscriptions',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>The fund <strong>$campaign</strong> is making a distribution dated <strong>$date</strong>. This distribution covers several of your subscriptions ($subscription_names) and the total amount payable to you is:</p>',
        highlight('$distrib_total_amount'),
        '<p>$pitch The distribution notices attached to this message detail, for each of your subscriptions, the amount distributed and the payment terms.</p>',
        '<p>No action is required on your side.</p>',
        cta('$url', 'Access my investor portal'),
        '<p>Our team remains available for any question regarding this distribution.</p>',
      ]),
    },
  },
  {
    slug: 'new_capital_account',
    name: 'Mise à disposition du capital account',
    section: 'distributions',
    recipient: 'investor',
    trigger: 'manual',
    origin:
      'Diffusion d\'un capital account aux investisseurs concernés depuis le back office, Fonds puis Capital accounts, action Notifier, avec le document en pièce jointe',
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$campaign',
      '$subscription.name',
      '$caname',
      '$date',
      '$message',
    ],
    proposedVariables: [],
    fr: {
      subject: '$campaign - Votre capital account au $date est disponible',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        '<p>Votre capital account <strong>$caname</strong>, arrêté au <strong>$date</strong>, est disponible pour votre souscription <strong>$subscription.name</strong> au fonds <strong>$campaign</strong>.</p>',
        '<p>$message Ce document, joint à ce message, présente la situation détaillée de votre souscription : montants appelés, distributions perçues et engagement restant.</p>',
        '<p>Il reste consultable à tout moment dans votre espace investisseur.</p>',
        cta('$url', 'Consulter mon capital account'),
        '<p>Notre équipe se tient à votre disposition pour toute question sur ce document.</p>',
      ]),
    },
    en: {
      subject: '$campaign - Your capital account as of $date is available',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>Your capital account <strong>$caname</strong>, as of <strong>$date</strong>, is available for your subscription <strong>$subscription.name</strong> to the fund <strong>$campaign</strong>.</p>',
        '<p>$message This document, attached to this message, presents the detailed position of your subscription: amounts called, distributions received and remaining commitment.</p>',
        '<p>It remains available at any time in your investor portal.</p>',
        cta('$url', 'View my capital account'),
        '<p>Our team remains available for any question regarding this document.</p>',
      ]),
    },
  },
  {
    slug: 'new_capital_account_bulk',
    name: 'Capital account regroupé mis à disposition',
    section: 'distributions',
    recipient: 'investor',
    trigger: 'manual',
    origin:
      "Diffusion d'un capital account depuis le back office quand plusieurs souscriptions du même investisseur sont regroupées dans un même envoi : un email unique, avec un document par souscription ou une notice combinée selon paramétrage",
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$campaign',
      '$caname',
      '$date',
      '$message',
    ],
    proposedVariables: [SUBSCRIPTION_NAMES],
    fr: {
      subject: '$campaign - Vos capital accounts au $date sont disponibles',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        '<p>Vos capital accounts <strong>$caname</strong>, arrêtés au <strong>$date</strong>, sont disponibles pour vos souscriptions ($subscription_names) au fonds <strong>$campaign</strong>.</p>',
        '<p>$message Les documents joints à ce message présentent, pour chacune de vos souscriptions, la situation détaillée : montants appelés, distributions perçues et engagement restant.</p>',
        '<p>Ils restent consultables à tout moment dans votre espace investisseur.</p>',
        cta('$url', 'Consulter mes capital accounts'),
        '<p>Notre équipe se tient à votre disposition pour toute question sur ces documents.</p>',
      ]),
    },
    en: {
      subject: '$campaign - Your capital accounts as of $date are available',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>Your capital accounts <strong>$caname</strong>, as of <strong>$date</strong>, are available for your subscriptions ($subscription_names) to the fund <strong>$campaign</strong>.</p>',
        '<p>$message The documents attached to this message present, for each of your subscriptions, the detailed position: amounts called, distributions received and remaining commitment.</p>',
        '<p>They remain available at any time in your investor portal.</p>',
        cta('$url', 'View my capital accounts'),
        '<p>Our team remains available for any question regarding these documents.</p>',
      ]),
    },
  },
  {
    slug: 'relance_capital_account',
    name: 'Relance de diffusion du capital account',
    section: 'distributions',
    recipient: 'investor',
    trigger: 'manual',
    origin:
      "Relance manuelle d'un capital account déjà diffusé, Fonds puis Capital accounts, action Relancer, avec le document de nouveau en pièce jointe",
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$campaign',
      '$subscription.name',
      '$caname',
      '$date',
      '$message',
    ],
    proposedVariables: [],
    fr: {
      subject: '$campaign - Rappel : votre capital account au $date est disponible',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        '<p>Nous vous rappelons que votre capital account <strong>$caname</strong>, arrêté au <strong>$date</strong>, est à votre disposition pour votre souscription <strong>$subscription.name</strong> au fonds <strong>$campaign</strong>.</p>',
        '<p>$message Ce document, joint de nouveau à ce message, présente la situation détaillée de votre souscription : montants appelés, distributions perçues et engagement restant.</p>',
        "<p>Aucune action n'est attendue de votre part.</p>",
        cta('$url', 'Consulter mon capital account'),
        '<p>Notre équipe se tient à votre disposition pour toute question sur ce document.</p>',
      ]),
    },
    en: {
      subject: '$campaign - Reminder: your capital account as of $date is available',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>This is a reminder that your capital account <strong>$caname</strong>, as of <strong>$date</strong>, is available for your subscription <strong>$subscription.name</strong> to the fund <strong>$campaign</strong>.</p>',
        '<p>$message This document, attached again to this message, presents the detailed position of your subscription: amounts called, distributions received and remaining commitment.</p>',
        '<p>No action is required on your side.</p>',
        cta('$url', 'View my capital account'),
        '<p>Our team remains available for any question regarding this document.</p>',
      ]),
    },
  },
  {
    slug: 'relance_capital_account_bulk',
    name: 'Relance de capital account regroupée',
    section: 'distributions',
    recipient: 'investor',
    trigger: 'manual',
    origin:
      "Relance d'un capital account déjà diffusé quand plusieurs souscriptions du même investisseur sont regroupées dans un même envoi, avec les documents de nouveau en pièce jointe",
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$campaign',
      '$caname',
      '$date',
      '$message',
    ],
    proposedVariables: [SUBSCRIPTION_NAMES],
    fr: {
      subject: '$campaign - Rappel : vos capital accounts au $date sont disponibles',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        '<p>Nous vous rappelons que vos capital accounts <strong>$caname</strong>, arrêtés au <strong>$date</strong>, sont à votre disposition pour vos souscriptions ($subscription_names) au fonds <strong>$campaign</strong>.</p>',
        '<p>$message Les documents joints de nouveau à ce message présentent, pour chacune de vos souscriptions, la situation détaillée : montants appelés, distributions perçues et engagement restant.</p>',
        "<p>Aucune action n'est attendue de votre part.</p>",
        cta('$url', 'Consulter mes capital accounts'),
        '<p>Notre équipe se tient à votre disposition pour toute question sur ces documents.</p>',
      ]),
    },
    en: {
      subject: '$campaign - Reminder: your capital accounts as of $date are available',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>This is a reminder that your capital accounts <strong>$caname</strong>, as of <strong>$date</strong>, are available for your subscriptions ($subscription_names) to the fund <strong>$campaign</strong>.</p>',
        '<p>$message The documents attached again to this message present, for each of your subscriptions, the detailed position: amounts called, distributions received and remaining commitment.</p>',
        '<p>No action is required on your side.</p>',
        cta('$url', 'View my capital accounts'),
        '<p>Our team remains available for any question regarding these documents.</p>',
      ]),
    },
  },
  {
    slug: 'deblocage',
    name: 'Avis de déblocage de parts',
    section: 'distributions',
    recipient: 'investor',
    trigger: 'manual',
    origin:
      "Notification d'une opération de déblocage aux investisseurs concernés depuis le back office, Fonds puis Déblocages, action Notifier, avec l'avis en pièce jointe",
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$prenom',
      '$nom',
      '$campaign',
      '$subscription.name',
      '$name',
      '$date',
      '$amount',
      '$charges',
      '$message',
    ],
    proposedVariables: [
      {
        name: '$nbshares',
        note: 'nombre de parts concernées par le déblocage, non passé au gabarit',
      },
    ],
    fr: {
      subject: '$campaign - Déblocage de parts : $amount à votre profit',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        "<p>Le fonds <strong>$campaign</strong> procède à l'opération de déblocage <strong>$name</strong>, en date du <strong>$date</strong>. Au titre de votre souscription <strong>$subscription.name</strong>, le montant débloqué s'élève à :</p>",
        highlight('$amount'),
        "<p>$message Les frais associés à cette opération s'élèvent à $charges. Votre avis de déblocage, joint à ce message, détaille le calcul et les modalités de versement.</p>",
        "<p>Aucune action n'est attendue de votre part.</p>",
        cta('$url', 'Consulter mon espace investisseur'),
        '<p>Notre équipe se tient à votre disposition pour toute question sur cette opération.</p>',
      ]),
    },
    en: {
      subject: '$campaign - Release of shares: $amount payable to you',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>The fund <strong>$campaign</strong> is carrying out the share release operation <strong>$name</strong>, dated <strong>$date</strong>. Under your subscription <strong>$subscription.name</strong>, the amount released is:</p>',
        highlight('$amount'),
        '<p>$message The fees related to this operation amount to $charges. Your release notice, attached to this message, details the calculation and the payment terms.</p>',
        '<p>No action is required on your side.</p>',
        cta('$url', 'Access my investor portal'),
        '<p>Our team remains available for any question regarding this operation.</p>',
      ]),
    },
  },
];
