import { cta, html, note, table } from './blocks';
import type { StarterPackTemplate } from './types';

/**
 * Section 8 : Rachats — page Confluence 930807810.
 *
 * Cycle de vie d'une demande de rachat : soumission par l'investisseur depuis son
 * espace, signature électronique du dossier, réouverture pour correction,
 * confirmation de signature complète, puis validation définitive par la société
 * de gestion.
 */
export const SECTION_08_REDEMPTIONS: StarterPackTemplate[] = [
  {
    slug: 'rebuy-submission',
    name: 'Accusé de réception de la demande de rachat',
    section: 'redemptions',
    recipient: 'investor',
    trigger: 'auto',
    origin:
      "Envoi automatique à la soumission de la demande de rachat par l'investisseur depuis son espace, parcours de rachat en ligne",
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$campaign',
      '$subscription_name',
      '$subscription',
      '$part',
      '$amount',
      '$nb_parts',
      '$iban',
    ],
    proposedVariables: [
      {
        name: '$investor.firstname',
        note: "famille socle non injectée ici : id_investor n'est pas passé dans les options du point d'appel, uniquement dans les identifiants de contexte",
      },
      {
        name: '$investor.lastname',
        note: "famille socle non injectée ici : id_investor n'est pas passé dans les options du point d'appel",
      },
      { name: '$submit_date', note: 'date de soumission, connue du rachat mais non passée' },
    ],
    fr: {
      subject: 'Votre demande de rachat sur $campaign a bien été reçue',
      html: html('fr', [
        '<p>Bonjour $investor.firstname $investor.lastname,</p>',
        '<p>Nous avons bien reçu votre demande de rachat sur le fonds <strong>$campaign</strong>, au titre de votre souscription <strong>$subscription_name</strong>, le $submit_date.</p>',
        table([
          ['Référence', '<strong>$subscription</strong>'],
          ['Part', '$part'],
          ['Nombre de parts', '$nb_parts'],
          ['Montant demandé', '<strong>$amount</strong>'],
          ['IBAN de règlement', '$iban'],
        ]),
        "<p>Votre demande va maintenant être examinée par la société de gestion. Vous serez informé par email de chaque étape, jusqu'à la validation définitive de votre rachat.</p>",
        cta('$url', 'Suivre ma demande'),
        '<p>Notre équipe se tient à votre disposition pour toute question sur votre demande de rachat.</p>',
      ]),
    },
    en: {
      subject: 'Your redemption request for $campaign has been received',
      html: html('en', [
        '<p>Dear $investor.firstname $investor.lastname,</p>',
        '<p>We have received your redemption request for the fund <strong>$campaign</strong>, under your subscription <strong>$subscription_name</strong>, on $submit_date.</p>',
        table([
          ['Reference', '<strong>$subscription</strong>'],
          ['Share', '$part'],
          ['Number of shares', '$nb_parts'],
          ['Requested amount', '<strong>$amount</strong>'],
          ['Payment IBAN', '$iban'],
        ]),
        '<p>Your request will now be reviewed by the management company. You will be notified by email at each step, up to the final validation of your redemption.</p>',
        cta('$url', 'Track my request'),
        '<p>Our team remains available for any question regarding your redemption request.</p>',
      ]),
    },
  },
  {
    slug: 'rebuy-submission-tovalid',
    name: 'Demande de rachat à traiter',
    section: 'redemptions',
    recipient: 'team',
    trigger: 'auto',
    origin:
      "Envoi automatique à la soumission de la demande de rachat par l'investisseur, vers l'adresse de validation des rachats paramétrée sur le fonds",
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$campaign',
      '$subscription_name',
      '$subscription',
      '$part',
      '$amount',
      '$nb_parts',
      '$iban',
      '$subscription_amount',
    ],
    proposedVariables: [
      {
        name: '$investor.fullname',
        note: "identité de l'investisseur ; famille socle non injectée ici car id_investor n'est pas passé dans les options du point d'appel",
      },
      {
        name: '$link',
        note: "lien direct vers l'écran Rachats du back office, non passé au gabarit",
      },
    ],
    fr: {
      subject: 'Nouvelle demande de rachat à traiter - $campaign - $subscription_name',
      html: html('fr', [
        '<p>Bonjour,</p>',
        "<p>Une nouvelle demande de rachat vient d'être soumise et attend votre prise en charge.</p>",
        table([
          ['Investisseur', '<strong>$investor.fullname</strong>'],
          ['Fonds', '$campaign'],
          [
            'Souscription',
            '$subscription - $subscription_name (montant souscrit : $subscription_amount)',
          ],
          ['Part', '$part'],
          ['Nombre de parts demandé', '$nb_parts'],
          ['Montant demandé', '<strong>$amount</strong>'],
          ['IBAN de règlement', '$iban'],
        ]),
        "<p>Selon le paramétrage du fonds, le dossier est à envoyer en signature ou à valider directement depuis l'écran Rachats du back-office.</p>",
        cta('$url', 'Traiter la demande'),
      ]),
    },
    en: {
      subject: 'New redemption request to process - $campaign - $subscription_name',
      html: html('en', [
        '<p>Hello,</p>',
        '<p>A new redemption request has just been submitted and awaits your review.</p>',
        table([
          ['Investor', '<strong>$investor.fullname</strong>'],
          ['Fund', '$campaign'],
          ['Subscription', '$subscription - $subscription_name (subscribed amount: $subscription_amount)'],
          ['Share', '$part'],
          ['Requested number of shares', '$nb_parts'],
          ['Requested amount', '<strong>$amount</strong>'],
          ['Payment IBAN', '$iban'],
        ]),
        '<p>Depending on the fund settings, the file must be sent for signature or validated directly from the Redemptions screen of the back office.</p>',
        cta('$url', 'Process the request'),
      ]),
    },
  },
  {
    slug: 'signature_rebuy',
    name: 'Invitation à signer le rachat',
    section: 'redemptions',
    recipient: 'investor',
    trigger: 'auto',
    origin:
      'Envoi automatique quand le dossier de rachat ponctuel part en signature électronique, ou quand le signataire suivant est notifié dans le cas de signatures séquencées',
    variables: [
      '$logo',
      '$appname',
      '$year',
      '$mirror',
      '$link',
      '$campaign',
      '$prenom',
      '$nom',
      '$contact_firstname',
      '$contact_lastname',
      '$contact_mail',
      '$subscriptionname',
    ],
    proposedVariables: [],
    fr: {
      subject: 'Votre dossier de rachat $campaign est prêt à signer',
      html: html('fr', [
        '<p>Bonjour $prenom $nom,</p>',
        '<p>Le dossier de rachat relatif à la souscription <strong>$subscriptionname</strong> sur le fonds <strong>$campaign</strong> est prêt pour la signature électronique.</p>',
        "<p>La signature ne prend que quelques minutes et s'effectue en ligne, de manière sécurisée.</p>",
        cta('$link', 'Signer mes documents'),
        '<p>Une fois toutes les signatures recueillies, vous recevrez une confirmation et le dossier sera transmis pour validation définitive.</p>',
        "<p>Pour toute question, vous pouvez contacter $contact_firstname $contact_lastname à l'adresse $contact_mail.</p>",
      ]),
    },
    en: {
      subject: 'Your redemption file for $campaign is ready to sign',
      html: html('en', [
        '<p>Dear $prenom $nom,</p>',
        '<p>The redemption file for subscription <strong>$subscriptionname</strong> on the fund <strong>$campaign</strong> is ready for electronic signature.</p>',
        '<p>Signing only takes a few minutes and is done online, securely.</p>',
        cta('$link', 'Sign my documents'),
        '<p>Once all signatures have been collected, you will receive a confirmation and the file will be forwarded for final validation.</p>',
        '<p>For any question, you can contact $contact_firstname $contact_lastname at $contact_mail.</p>',
      ]),
    },
  },
  {
    slug: 'reopen-rebuy',
    name: 'Demande de rachat réouverte pour correction',
    section: 'redemptions',
    recipient: 'investor',
    trigger: 'manual',
    origin:
      'Réouverture d\'un rachat déjà soumis ou signé par un utilisateur GP depuis la vue 360 du rachat, Fonds puis Rachats, avec saisie d\'un motif. Adressé au distributeur seul si le réglage "Send rebuys reopen to partner only" est actif',
    variables: [
      '$logo',
      '$appname',
      '$year',
      '$mirror',
      '$message',
      '$id_souscription',
      '$link',
      '$investor.firstname',
      '$investor.lastname',
      '$campaign.name',
    ],
    proposedVariables: [],
    fr: {
      subject: 'Votre demande de rachat $id_souscription est à corriger',
      html: html('fr', [
        '<p>Bonjour $investor.firstname $investor.lastname,</p>',
        "<p>Votre demande de rachat <strong>$id_souscription</strong> sur le fonds <strong>$campaign.name</strong> a été réouverte par nos équipes afin d'y apporter une correction.</p>",
        '<p><strong>Motif de la réouverture :</strong></p>',
        note('$message'),
        '<p>Nous vous invitons à reprendre votre demande, à apporter les corrections nécessaires puis à la soumettre à nouveau.</p>',
        cta('$link', 'Reprendre ma demande'),
        '<p>Une fois soumise à nouveau, votre demande suivra le circuit de validation habituel.</p>',
      ]),
    },
    en: {
      subject: 'Your redemption request $id_souscription requires a correction',
      html: html('en', [
        '<p>Dear $investor.firstname $investor.lastname,</p>',
        '<p>Your redemption request <strong>$id_souscription</strong> on the fund <strong>$campaign.name</strong> has been reopened by our team so that a correction can be made.</p>',
        '<p><strong>Reason for reopening:</strong></p>',
        note('$message'),
        '<p>Please resume your request, make the necessary corrections and submit it again.</p>',
        cta('$link', 'Resume my request'),
        '<p>Once resubmitted, your request will follow the usual validation process.</p>',
      ]),
    },
  },
  {
    slug: 'confirm-rebuy-investor',
    name: 'Confirmation de rachat signé',
    section: 'redemptions',
    recipient: 'investor',
    trigger: 'auto',
    origin:
      'Envoi automatique quand toutes les signatures du dossier de rachat sont recueillies et que le rachat passe au statut signé',
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$firstname',
      '$lastname',
      '$campaign',
      '$subscriptionname',
      '$nb',
    ],
    proposedVariables: [],
    fr: {
      subject: 'Votre demande de rachat sur $campaign est entièrement signée',
      html: html('fr', [
        '<p>Bonjour $firstname $lastname,</p>',
        '<p>Toutes les signatures de votre dossier de rachat ont été recueillies. Votre demande portant sur la souscription <strong>$subscriptionname</strong> du fonds <strong>$campaign</strong> est désormais signée.</p>',
        '<p>Elle est transmise à la société de gestion pour validation définitive. Vous recevrez une confirmation précisant le nombre de parts et le montant définitivement rachetés.</p>',
        cta('$url', 'Consulter mon espace investisseur'),
        '<p>Vos documents signés sont disponibles dans votre espace.</p>',
      ]),
    },
    en: {
      subject: 'Your redemption request for $campaign is fully signed',
      html: html('en', [
        '<p>Dear $firstname $lastname,</p>',
        '<p>All signatures for your redemption file have been collected. Your request regarding subscription <strong>$subscriptionname</strong> on the fund <strong>$campaign</strong> is now signed.</p>',
        '<p>It has been forwarded to the management company for final validation. You will receive a confirmation stating the final number of shares and amount redeemed.</p>',
        cta('$url', 'Access my investor portal'),
        '<p>Your signed documents are available in your portal.</p>',
      ]),
    },
  },
  {
    slug: 'valid-rebuy',
    name: 'Validation définitive du rachat',
    section: 'redemptions',
    recipient: 'investor',
    trigger: 'manual',
    origin:
      'Validation du rachat par un utilisateur GP depuis le back office, Fonds puis Rachats, avec saisie du nombre de parts définitif',
    variables: [
      '$logo',
      '$appname',
      '$url',
      '$year',
      '$mirror',
      '$firstname',
      '$lastname',
      '$campaign',
      '$subscriptionname',
      '$amtornb',
      '$nb_real',
      '$vl_vente',
      '$vl_vente_date',
      '$date_added',
      '$date',
    ],
    proposedVariables: [
      {
        name: '$amount_final',
        note: "montant définitif du rachat calculé à la validation, non passé au gabarit ; seuls le nombre de parts définitif et le montant demandé initialement sont disponibles",
      },
      { name: '$payment_date', note: 'date prévisionnelle de règlement' },
    ],
    fr: {
      subject: '$campaign - Votre rachat est validé',
      html: html('fr', [
        '<p>Bonjour $firstname $lastname,</p>',
        '<p>Votre demande de rachat sur le fonds <strong>$campaign</strong>, au titre de la souscription <strong>$subscriptionname</strong>, a été définitivement validée par la société de gestion.</p>',
        table([
          ['Demande initiale', '$amtornb (le $date_added)'],
          ['Nombre de parts rachetées', '<strong>$nb_real</strong>'],
          ['Valeur liquidative retenue', '$vl_vente (au $vl_vente_date)'],
          ["Date d'exécution", '$date'],
          ['Montant du rachat', '<strong>$amount_final</strong>'],
        ]),
        '<p>Le règlement sera effectué par virement sur le compte bancaire communiqué lors de votre demande, avant le <strong>$payment_date</strong>.</p>',
        cta('$url', 'Consulter mon espace investisseur'),
        '<p>Notre équipe se tient à votre disposition pour toute question sur ce rachat.</p>',
      ]),
    },
    en: {
      subject: '$campaign - Your redemption has been validated',
      html: html('en', [
        '<p>Dear $firstname $lastname,</p>',
        '<p>Your redemption request on the fund <strong>$campaign</strong>, under subscription <strong>$subscriptionname</strong>, has been finally validated by the management company.</p>',
        table([
          ['Initial request', '$amtornb (on $date_added)'],
          ['Number of shares redeemed', '<strong>$nb_real</strong>'],
          ['Net asset value applied', '$vl_vente (as of $vl_vente_date)'],
          ['Execution date', '$date'],
          ['Redemption amount', '<strong>$amount_final</strong>'],
        ]),
        '<p>Payment will be made by wire transfer to the bank account provided with your request, by <strong>$payment_date</strong>.</p>',
        cta('$url', 'Access my investor portal'),
        '<p>Our team remains available for any question regarding this redemption.</p>',
      ]),
    },
  },
  {
    slug: 'confirm-rebuy',
    name: 'Rachat entièrement signé, notification interne',
    section: 'redemptions',
    recipient: 'team',
    trigger: 'auto',
    origin:
      "Envoi automatique quand toutes les signatures du dossier de rachat sont recueillies, vers l'adresse de validation des rachats paramétrée sur le fonds",
    variables: [
      '$logo',
      '$appname',
      '$year',
      '$mirror',
      '$firstname',
      '$lastname',
      '$company_name',
      '$fund',
      '$subscriptionname',
      '$nb',
      '$partner',
      '$partneruser',
      '$link',
    ],
    proposedVariables: [],
    fr: {
      subject: 'Rachat entièrement signé à valider - $fund - $subscriptionname',
      html: html('fr', [
        '<p>Bonjour,</p>',
        "<p>Le dossier de rachat suivant vient d'être entièrement signé et attend la validation définitive :</p>",
        table([
          ['Investisseur', '<strong>$firstname $lastname $company_name</strong>'],
          ['Fonds', '$fund'],
          ['Souscription', '$subscriptionname'],
          ['Nombre de parts demandé', '$nb'],
          ['Distributeur', '$partner ($partneruser)'],
        ]),
        "<p>La validation définitive s'effectue depuis l'écran Rachats du fonds, en saisissant le nombre de parts et le montant définitifs.</p>",
        cta('$link', 'Traiter le rachat'),
      ]),
    },
    en: {
      subject: 'Fully signed redemption to validate - $fund - $subscriptionname',
      html: html('en', [
        '<p>Hello,</p>',
        '<p>The following redemption file has just been fully signed and awaits final validation:</p>',
        table([
          ['Investor', '<strong>$firstname $lastname $company_name</strong>'],
          ['Fund', '$fund'],
          ['Subscription', '$subscriptionname'],
          ['Requested number of shares', '$nb'],
          ['Distributor', '$partner ($partneruser)'],
        ]),
        "<p>Final validation is performed from the fund's Redemptions screen, by entering the final number of shares and amount.</p>",
        cta('$link', 'Process the redemption'),
      ]),
    },
  },
];
