import { useState, useEffect, useMemo } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  X,
  Zap,
  Eye,
  Send,
  FileText,
  Users,
  CheckCircle2,
} from 'lucide-react';
import { Button } from './ui/button';
import { cn } from './ui/utils';
import {
  Timeline,
  type TimelineEvent,
  type TimelineCsvColumn,
} from './ui/timeline';
import { DocumentRelaunchModal } from './DocumentRelaunchModal';
import {
  getBirdviewActivityTypes,
  type BirdviewActivityEventCode,
} from '../utils/birdviewActivityCatalog';
import { useTranslation } from '../utils/languageContext';
import {
  buildActivityEvents,
  contextFromDoc,
} from '../utils/documentActivityGenerator';

type ActivityType = BirdviewActivityEventCode;

type UserType = 'Investor' | 'Contact' | 'Advisor';

interface ActivitySource {
  id: string;
  type: ActivityType;
  userName: string;
  userEmail: string;
  userType: UserType;
  /** ISO-8601 datetime string. Always the source of truth for date/time display. */
  timestamp: string;
  /** Required when userType === 'Contact' — name of the investor this contact is linked to. */
  primaryInvestor?: string;
}

interface DocumentActivityPanelProps {
  isOpen: boolean;
  onClose: () => void;
  documentName: string;
  documentId: string;
  isNominatif?: boolean;
  /** LP entity name (when isNominatif). Used to source the real contacts. */
  investorRestriction?: string;
  /** Fund the document belongs to — used to scope generic-doc recipients. */
  fundRestriction?: string;
  /** Optional segment restrictions for marketing / segment-targeted docs. */
  segmentRestrictions?: string[];
  /** Subscription id (for nominatif docs) — surfaced in the timeline. */
  subscriptionRestriction?: string;
  /**
   * BirdView contextual scope. When set, the timeline + stats are
   * narrowed to the selected investor (and optionally contact). Pass
   * undefined to show the doc's full audience.
   */
  viewerScope?: { investorName?: string; contactName?: string };
}

// ---------------------------------------------------------------------------
// Activity events — generated by the shared deterministic generator so
// the numbers shown here always match the BirdView tree engagement and
// the relaunch modal recipient list. No randomization.
// ---------------------------------------------------------------------------

interface DocContext {
  isNominatif: boolean;
  documentName: string;
  investorRestriction?: string;
  fundRestriction?: string;
  segmentRestrictions?: string[];
  viewerScope?: { investorName?: string; contactName?: string };
}

const buildActivitiesForDocument = (ctx: DocContext): ActivitySource[] =>
  buildActivityEvents(
    contextFromDoc({
      name: ctx.documentName,
      isNominatif: ctx.isNominatif,
      investorRestriction: ctx.investorRestriction,
      fundRestriction: ctx.fundRestriction,
      segmentRestrictions: ctx.segmentRestrictions,
      viewerScope: ctx.viewerScope,
    }),
  ).map((e) => ({
    id: e.id,
    type: e.type as ActivityType,
    userName: e.userName,
    userEmail: e.userEmail,
    userType: e.userType,
    timestamp: e.timestamp,
    primaryInvestor: e.primaryInvestor,
  }));

// ---------------------------------------------------------------------------
// Timeline type descriptors (shared icon + label map)
// ---------------------------------------------------------------------------

type TFn = (key: string, vars?: Record<string, string | number>) => string;

// Map the domain-specific source to the neutral TimelineEvent shape.
const toTimelineEvent = (
  source: ActivitySource,
  t: TFn,
): TimelineEvent<ActivityType> => ({
  id: source.id,
  type: source.type,
  timestamp: source.timestamp,
  actorName: source.userName,
  actorSublabel: source.userEmail,
  actorRole: t(`ged.activityPanel.userType.${source.userType}`),
  description:
    source.userType === 'Contact' && source.primaryInvestor ? (
      <span className="inline-flex items-center gap-1">
        <Users className="w-3 h-3" />
        {t('ged.activityPanel.attachedTo')}{' '}
        <span className="font-medium text-foreground">
          {source.primaryInvestor}
        </span>
      </span>
    ) : undefined,
  meta: {
    userType: source.userType,
    primaryInvestor: source.primaryInvestor,
  },
});

// ---------------------------------------------------------------------------
// Engagement computation (domain-specific, kept local)
// ---------------------------------------------------------------------------

interface EngagementResult {
  label: string;
  sublabel: string;
  /** 0–100 for the progress ring. */
  percent: number;
  /** success / warning / neutral for color accent. */
  tone: 'success' | 'warning' | 'neutral';
}

const computeEngagement = (
  events: ActivitySource[],
  isNominatif: boolean,
  t: TFn,
): EngagementResult => {
  const viewedEvents = events.filter(
    (e) =>
      e.type === 'document_viewed' ||
      e.type === 'document_downloaded' ||
      e.type === 'document_validated',
  );

  if (isNominatif) {
    const viewers = new Set(viewedEvents.map((e) => e.userEmail));
    const recipients = new Set(events.map((e) => e.userEmail));
    const count = viewers.size;
    const total = recipients.size;
    return {
      label: count > 0 ? t('ged.activityPanel.engagement.viewed') : t('ged.activityPanel.engagement.notViewed'),
      sublabel:
        count > 0
          ? t(count > 1 ? 'ged.activityPanel.engagement.byContactsMany' : 'ged.activityPanel.engagement.byContactsOne', { count, total })
          : t('ged.activityPanel.engagement.noRecipientOpened'),
      percent: count > 0 ? 100 : 0,
      tone: count > 0 ? 'success' : 'neutral',
    };
  }

  const investorEvents = events.filter((e) => e.userType === 'Investor');
  const allInvestors = new Set(investorEvents.map((e) => e.userEmail));
  const viewedInvestors = new Set(
    viewedEvents.filter((e) => e.userType === 'Investor').map((e) => e.userEmail),
  );
  const total = allInvestors.size;
  const count = viewedInvestors.size;
  const percent = total === 0 ? 0 : Math.round((count / total) * 100);
  const tone: EngagementResult['tone'] =
    percent >= 75 ? 'success' : percent >= 35 ? 'warning' : 'neutral';
  return {
    label: t(total > 1 ? 'ged.activityPanel.engagement.investorsRatioMany' : 'ged.activityPanel.engagement.investorsRatioOne', { count, total }),
    sublabel: t('ged.activityPanel.engagement.investorsViewed'),
    percent,
    tone,
  };
};

const buildExportColumns = (
  t: TFn,
  activityTypes: ReturnType<typeof getBirdviewActivityTypes>,
  locale: string,
): TimelineCsvColumn<ActivityType>[] => [
  {
    header: t('ged.activityPanel.export.date'),
    value: (ev) => new Date(ev.timestamp).toLocaleDateString(locale),
  },
  {
    header: t('ged.activityPanel.export.time'),
    value: (ev) =>
      new Date(ev.timestamp).toLocaleTimeString(locale, {
        hour: '2-digit',
        minute: '2-digit',
      }),
  },
  {
    header: t('ged.activityPanel.export.eventType'),
    value: (ev) => activityTypes[ev.type]?.label ?? String(ev.type),
  },
  { header: t('ged.activityPanel.export.user'), value: (ev) => ev.actorName ?? '' },
  { header: t('ged.activityPanel.export.email'), value: (ev) => ev.actorSublabel ?? '' },
  { header: t('ged.activityPanel.export.userType'), value: (ev) => ev.actorRole ?? '' },
  {
    header: t('ged.activityPanel.export.primaryInvestor'),
    value: (ev) => (ev.meta?.primaryInvestor as string | undefined) ?? '',
  },
];

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function DocumentActivityPanel({
  isOpen,
  onClose,
  documentName,
  documentId,
  isNominatif = true,
  investorRestriction,
  fundRestriction,
  segmentRestrictions,
  subscriptionRestriction: _subscriptionRestriction,
  viewerScope,
}: DocumentActivityPanelProps) {
  const { t, lang } = useTranslation();
  const activityTypes = useMemo(() => getBirdviewActivityTypes(lang), [lang]);
  const [activities, setActivities] = useState<ActivitySource[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isRelaunchModalOpen, setIsRelaunchModalOpen] = useState(false);

  useEffect(() => {
    if (isOpen) {
      setIsLoading(true);
      const timer = setTimeout(() => {
        const source = buildActivitiesForDocument({
          documentName,
          isNominatif,
          investorRestriction,
          fundRestriction,
          segmentRestrictions,
          viewerScope,
        });
        setActivities(source);
        setIsLoading(false);
      }, 300);
      return () => clearTimeout(timer);
    }
  }, [
    isOpen, documentId, isNominatif,
    investorRestriction, fundRestriction, segmentRestrictions?.join('|'),
    viewerScope?.investorName, viewerScope?.contactName,
  ]);

  const timelineEvents = useMemo(
    () => activities.map((a) => toTimelineEvent(a, t)),
    [activities, t],
  );

  const engagement = useMemo(
    () => computeEngagement(activities, isNominatif, t),
    [activities, isNominatif, t],
  );

  const exportColumns = useMemo(
    () => buildExportColumns(t, activityTypes, lang === 'en' ? 'en-US' : 'fr-FR'),
    [t, activityTypes, lang],
  );

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/40 backdrop-blur-sm z-40"
          />

          {/* Panel */}
          <motion.div
            initial={{ x: '100%' }}
            animate={{ x: 0 }}
            exit={{ x: '100%' }}
            transition={{ type: 'spring', damping: 30, stiffness: 300 }}
            className="fixed top-0 right-0 h-full w-[560px] max-w-full bg-white text-foreground shadow-2xl z-50 flex flex-col border-l border-border"
            style={{ backgroundColor: '#FFFFFF' }}
          >
            {/* Header */}
            <div className="flex items-start gap-3 px-6 py-5 border-b border-border bg-white" style={{ backgroundColor: '#FFFFFF' }}>
              <div
                className="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 shadow-brand"
                style={{
                  background:
                    'linear-gradient(135deg, var(--brand-primary) 0%, var(--brand-accent) 100%)',
                }}
              >
                <Zap className="w-5 h-5 text-white" />
              </div>
              <div className="flex-1 min-w-0">
                <h2 className="text-lg font-semibold text-foreground">
                  {t('ged.activityPanel.title')}
                </h2>
                <p className="text-sm text-muted-foreground">
                  {t('ged.activityPanel.subtitle')}
                </p>
              </div>
              <button
                onClick={onClose}
                aria-label={t('ged.activityPanel.closeAria')}
                className="p-2 hover:bg-muted rounded-lg transition-colors"
              >
                <X className="w-5 h-5 text-muted-foreground" />
              </button>
            </div>

            {/* Document info + engagement KPI + Relancer */}
            <div className="px-6 py-4 space-y-3 bg-white border-b border-border" style={{ backgroundColor: '#FFFFFF' }}>
              <div className="flex items-center gap-2 rounded-md border border-border bg-white px-3 py-2">
                <FileText className="w-4 h-4 text-muted-foreground flex-shrink-0" />
                <span className="text-sm font-medium text-foreground truncate">
                  {documentName}
                </span>
                <span className="ml-auto text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
                  {isNominatif ? t('ged.activityPanel.nominative') : t('ged.activityPanel.generic')}
                </span>
              </div>

              {isNominatif ? (
                /* Nominatif: compact single-row layout */
                <div className="flex items-center gap-3 rounded-md border border-border bg-white px-3 py-2.5">
                  <div className="relative w-12 h-12 flex-shrink-0">
                    <svg className="w-12 h-12 -rotate-90" viewBox="0 0 36 36">
                      <circle cx="18" cy="18" r="15.9155" className="stroke-border" strokeWidth="3" fill="none" />
                      <circle
                        cx="18" cy="18" r="15.9155"
                        className={cn(engagement.tone === 'success' ? 'stroke-brand-success' : 'stroke-muted-foreground/50')}
                        strokeWidth="3" fill="none"
                        strokeDasharray={`${engagement.percent}, 100`}
                        strokeLinecap="round"
                      />
                    </svg>
                    <div className="absolute inset-0 flex items-center justify-center">
                      {engagement.tone === 'success' ? (
                        <CheckCircle2 className="w-5 h-5 text-brand-success" />
                      ) : (
                        <Eye className="w-4 h-4 text-muted-foreground" />
                      )}
                    </div>
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="text-sm font-medium text-foreground truncate">{engagement.label}</div>
                    <div className="text-xs text-muted-foreground truncate">{engagement.sublabel}</div>
                  </div>
                  <Button
                    size="sm"
                    onClick={() => setIsRelaunchModalOpen(true)}
                    className="text-white border-0 flex-shrink-0"
                    style={{ background: 'linear-gradient(135deg, var(--brand-primary) 0%, var(--brand-accent) 100%)' }}
                  >
                    <Send className="w-3.5 h-3.5" />
                    {t('ged.activityPanel.relaunch')}
                  </Button>
                </div>
              ) : (
                /* Générique: enhanced layout with prominent percentage */
                <div className="rounded-lg border border-border bg-white overflow-hidden">
                  <div className="flex items-center gap-4 px-4 py-3">
                    {/* Large progress ring */}
                    <div className="relative w-16 h-16 flex-shrink-0">
                      <svg className="w-16 h-16 -rotate-90" viewBox="0 0 36 36">
                        <circle cx="18" cy="18" r="15.9155" className="stroke-border" strokeWidth="2.5" fill="none" />
                        <circle
                          cx="18" cy="18" r="15.9155"
                          className={cn(
                            engagement.tone === 'success'
                              ? 'stroke-brand-success'
                              : engagement.tone === 'warning'
                                ? 'stroke-amber-500'
                                : 'stroke-muted-foreground/50',
                          )}
                          strokeWidth="2.5" fill="none"
                          strokeDasharray={`${engagement.percent}, 100`}
                          strokeLinecap="round"
                        />
                      </svg>
                      <div className="absolute inset-0 flex items-center justify-center">
                        <span
                          className={cn(
                            'text-base font-bold',
                            engagement.tone === 'success'
                              ? 'text-brand-success'
                              : engagement.tone === 'warning'
                                ? 'text-amber-600'
                                : 'text-muted-foreground',
                          )}
                        >
                          {engagement.percent}%
                        </span>
                      </div>
                    </div>

                    {/* Text + sub-bar */}
                    <div className="flex-1 min-w-0 space-y-1.5">
                      <div className="text-sm font-semibold text-foreground">
                        {engagement.label}
                      </div>
                      <div className="text-xs text-muted-foreground">
                        {engagement.sublabel}
                      </div>
                      {/* Mini progress bar */}
                      <div className="h-1.5 w-full rounded-full bg-muted overflow-hidden">
                        <div
                          className={cn(
                            'h-full rounded-full transition-all duration-500',
                            engagement.tone === 'success'
                              ? 'bg-brand-success'
                              : engagement.tone === 'warning'
                                ? 'bg-amber-500'
                                : 'bg-muted-foreground/50',
                          )}
                          style={{ width: `${engagement.percent}%` }}
                        />
                      </div>
                    </div>

                    {/* Relancer */}
                    <Button
                      size="sm"
                      onClick={() => setIsRelaunchModalOpen(true)}
                      className="text-white border-0 flex-shrink-0"
                      style={{ background: 'linear-gradient(135deg, var(--brand-primary) 0%, var(--brand-accent) 100%)' }}
                    >
                      <Send className="w-3.5 h-3.5" />
                      {t('ged.activityPanel.relaunch')}
                    </Button>
                  </div>
                </div>
              )}
            </div>

            {/* Timeline (shared, neutral DS component) */}
            <div className="flex-1 overflow-y-auto scrollbar-thin bg-white px-6 py-2" style={{ backgroundColor: '#FFFFFF' }}>
              <Timeline<ActivityType>
                events={timelineEvents}
                types={activityTypes}
                isLoading={isLoading}
                pageSize={6}
                exportFileName={t('ged.activityPanel.export.fileName', { name: documentName })}
                exportColumns={exportColumns}
                emptyLabel={t('ged.activityPanel.emptyLabel')}
              />
            </div>
          </motion.div>

          {/* Relaunch Modal */}
          <DocumentRelaunchModal
            documentId={documentId}
            documentName={documentName}
            isNominatif={isNominatif}
            investorRestriction={investorRestriction}
            fundRestriction={fundRestriction}
            segmentRestrictions={segmentRestrictions}
            viewerScope={viewerScope}
            isOpen={isRelaunchModalOpen}
            onClose={() => setIsRelaunchModalOpen(false)}
          />
        </>
      )}
    </AnimatePresence>
  );
}
